branches:
  only:
    - master
language: objective-c
osx_image: xcode8
install:
- gem install xcpretty -N --no-ri --no-rdoc
script:
- set -o pipefail && xcodebuild -project YangMingShanDemo.xcodeproj -scheme YangMingShanDemo -sdk iphonesimulator8.1 -destination 'platform=iOS Simulator,name=iPhone 7,OS=8.1' build test | xcpretty -c
