branches:
  only:
    - master
language: objective-c
osx_image: xcode8.0
install:
- gem install xcpretty -N --no-ri --no-rdoc
script:
- set -o pipefail && xcodebuild -project YangMingShanDemo.xcodeproj -scheme YangMingShanDemo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' build test | xcpretty -c