branches:
  only:
    - master
language: objective-c
osx_image: xcode8.0
install:
- gem install xcpretty -N --no-ri --no-rdoc
script:
- set -o pipefail && xcodebuild -project YangMingShanDemo.xcodeproj -scheme YangMingShanDemo -sdk iphonesimulator10.0 -destination 'OS=10.0, name=iPhone 7 Plus' build test | xcpretty -c