branches:
  only:
    - master
language: objective-c
osx_image: xcode8.3
install:
- gem install xcpretty -N --no-ri --no-rdoc
script:
- set -o pipefail && xcodebuild -project YangMingShanDemo.xcodeproj -scheme YangMingShanDemo -sdk iphonesimulator10.3 -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' build test | xcpretty -c
